# Generated by Django 5.2.4 on 2025-08-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Colecao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_tombo", models.CharField(max_length=100)),
                ("reino", models.CharField(max_length=100)),
                ("filo", models.CharField(max_length=100)),
                ("classe", models.CharField(max_length=100)),
                ("ordem", models.CharField(max_length=100)),
                ("familia", models.CharField(max_length=100)),
                ("genero", models.CharField(max_length=100)),
                ("epiteto", models.CharField(max_length=100)),
                ("local", models.CharField(max_length=100)),
                ("continente", models.CharField(max_length=100)),
                ("municipio", models.CharField(max_length=100)),
                ("estado", models.CharField(max_length=100)),
                ("pais", models.CharField(max_length=100)),
                ("latitude", models.CharField(max_length=100)),
                ("longitude", models.CharField(max_length=100)),
                ("data", models.DateField()),
                ("coletores_1_last_name", models.CharField(max_length=100)),
                ("coletores_1_first_name", models.CharField(max_length=100)),
                (
                    "coletores_2_last_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "coletores_2_first_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "coletores_3_last_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "coletores_3_first_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "coletores_4_last_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "coletores_4_first_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "coletores_5_last_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "coletores_5_first_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "coletores_6_last_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "coletores_6_first_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "coletores_7_last_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "coletores_7_first_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("determinador_1_last_name", models.CharField(max_length=100)),
                ("determinador_1_first_name", models.CharField(max_length=100)),
                (
                    "determinador_2_last_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "determinador_2_first_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "determinador_3_last_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "determinador_3_first_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "determinador_4_last_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "determinador_4_first_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "determinador_5_last_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "determinador_5_first_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "determinador_6_last_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "determinador_6_first_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "determinador_7_last_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "determinador_7_first_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("curador_last_name", models.CharField(max_length=100)),
                ("curador_first_name", models.CharField(max_length=100)),
                ("observacao", models.TextField(blank=True, null=True)),
                ("numero_total_exemplares", models.IntegerField()),
                ("numero_femeas_ovigeras", models.IntegerField()),
                ("numero_femeas", models.IntegerField()),
                ("numero_machos", models.IntegerField()),
                ("conservacao", models.CharField(max_length=100)),
                ("projeto", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=100)),
            ],
        ),
    ]
