# Generated by Django 5.1.4 on 2025-08-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colecao", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colecao",
            name="numero_tombo",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
