# Generated by Django 5.2.4 on 2025-08-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colecao", "0002_alter_colecao_numero_tombo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="colecao",
            name="data",
        ),
        migrations.AddField(
            model_name="colecao",
            name="data_coleta",
            field=models.DateField(blank=True, null=True),
        ),
    ]
