# Generated by Django 5.2.4 on 2025-08-05 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("colecao", "0003_remove_colecao_data_colecao_data_coleta"),
    ]

    operations = [
        migrations.RenameField(
            model_name="colecao",
            old_name="data_coleta",
            new_name="data",
        ),
    ]
