# Generated by Django 5.2.4 on 2025-08-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colecao", "0004_rename_data_coleta_colecao_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colecao",
            name="classe",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="coletores_1_first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="coletores_1_last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="continente",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="data",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="epiteto",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="estado",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="familia",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="filo",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="genero",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="latitude",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="local",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="longitude",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="municipio",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="ordem",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="pais",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="reino",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
