# Generated by Django 5.2.4 on 2025-08-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colecao", "0005_alter_colecao_classe_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colecao",
            name="numero_tombo",
            field=models.CharField(max_length=100),
        ),
    ]
