# Generated by Django 5.2.4 on 2025-10-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colecao", "0006_alter_colecao_numero_tombo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colecao",
            name="classe",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="coletores_1_first_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="coletores_1_last_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="coletores_2_first_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="coletores_2_last_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="coletores_3_first_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="coletores_3_last_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="coletores_4_first_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="coletores_4_last_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="coletores_5_first_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="coletores_5_last_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="coletores_6_first_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="coletores_6_last_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="coletores_7_first_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="coletores_7_last_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="conservacao",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="continente",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="curador_first_name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="curador_last_name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="data",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="determinador_1_first_name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="determinador_1_last_name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="determinador_2_first_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="determinador_2_last_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="determinador_3_first_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="determinador_3_last_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="determinador_4_first_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="determinador_4_last_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="determinador_5_first_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="determinador_5_last_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="determinador_6_first_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="determinador_6_last_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="determinador_7_first_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="determinador_7_last_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="epiteto",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="estado",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="familia",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="filo",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="genero",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="latitude",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="local",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="longitude",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="municipio",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="numero_tombo",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="ordem",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="pais",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="projeto",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="reino",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="colecao",
            name="status",
            field=models.CharField(max_length=200),
        ),
    ]
