from django.db import models

class Colecao(models.Model):
    numero_tombo = models.CharField(max_length=200)
    reino = models.CharField(max_length=200, blank=True, null=True)
    filo = models.CharField(max_length=200, blank=True, null=True)
    classe = models.CharField(max_length=200, blank=True, null=True)
    ordem = models.CharField(max_length=200, blank=True, null=True)
    familia = models.CharField(max_length=200, blank=True, null=True)
    genero = models.CharField(max_length=200, blank=True, null=True)
    epiteto = models.CharField(max_length=200, blank=True, null=True)
    local = models.CharField(max_length=200, blank=True, null=True)
    continente = models.CharField(max_length=200, blank=True, null=True)
    municipio = models.CharField(max_length=200, blank=True, null=True)
    estado = models.CharField(max_length=200, blank=True, null=True)
    pais = models.CharField(max_length=200, blank=True, null=True)
    latitude = models.CharField(max_length=200, blank=True, null=True)
    longitude = models.CharField(max_length=200, blank=True, null=True)
    data = models.CharField(max_length=200, blank=True, null=True)
    coletores_1_last_name = models.CharField(max_length=200, blank=True, null=True)
    coletores_1_first_name = models.CharField(max_length=200, blank=True, null=True)
    coletores_2_last_name = models.CharField(max_length=200, blank=True, null=True)
    coletores_2_first_name = models.CharField(max_length=200, blank=True,null=True)
    coletores_3_last_name = models.CharField(max_length=200, blank=True, null=True)
    coletores_3_first_name = models.CharField(max_length=200, blank=True, null=True)
    coletores_4_last_name = models.CharField(max_length=200, blank=True, null=True)
    coletores_4_first_name = models.CharField(max_length=200, blank=True, null=True)
    coletores_5_last_name = models.CharField(max_length=200, blank=True, null=True)
    coletores_5_first_name = models.CharField(max_length=200, blank=True, null=True)
    coletores_6_last_name = models.CharField(max_length=200, blank=True, null=True)
    coletores_6_first_name = models.CharField(max_length=200, blank=True, null=True)
    coletores_7_last_name = models.CharField(max_length=200, blank=True, null=True)
    coletores_7_first_name = models.CharField(max_length=200, blank=True, null=True)
    determinador_1_last_name = models.CharField(max_length=200)
    determinador_1_first_name = models.CharField(max_length=200)
    determinador_2_last_name = models.CharField(max_length=200, blank=True,null=True)
    determinador_2_first_name = models.CharField(max_length=200, blank=True,null=True)
    determinador_3_last_name = models.CharField(max_length=200, blank=True, null=True)
    determinador_3_first_name = models.CharField(max_length=200, blank=True,null=True)
    determinador_4_last_name = models.CharField(max_length=200, blank=True, null=True)
    determinador_4_first_name = models.CharField(max_length=200, blank=True,null=True)
    determinador_5_last_name = models.CharField(max_length=200, blank=True, null=True)
    determinador_5_first_name = models.CharField(max_length=200, blank=True,null=True)
    determinador_6_last_name = models.CharField(max_length=200, blank=True, null=True)
    determinador_6_first_name = models.CharField(max_length=200, blank=True,null=True)
    determinador_7_last_name = models.CharField(max_length=200, blank=True, null=True)
    determinador_7_first_name = models.CharField(max_length=200, blank=True,null=True)
    curador_last_name = models.CharField(max_length=200)
    curador_first_name = models.CharField(max_length=200)
    observacao = models.TextField(blank=True, null=True)
    numero_total_exemplares = models.IntegerField()
    numero_femeas_ovigeras = models.IntegerField()
    numero_femeas = models.IntegerField()
    numero_machos = models.IntegerField()
    conservacao = models.CharField(max_length=200)
    projeto = models.CharField(max_length=200)
    status = models.CharField(max_length=200)
    
    def __str__(self):
        return self.nome